// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAacB0ISL3dOqTkyyetrI5jZ9Q53nEwdZk',
    appId: '1:609816954407:web:ed2ed1afaf47df11d63002',
    messagingSenderId: '609816954407',
    projectId: 'flutter-project-6004e',
    authDomain: 'flutter-project-6004e.firebaseapp.com',
    storageBucket: 'flutter-project-6004e.firebasestorage.app',
    measurementId: 'G-69XP27FDCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyDuBem-q8GtECQX8LmePh0iWntlEvZ7I',
    appId: '1:609816954407:android:131bf128f180c85bd63002',
    messagingSenderId: '609816954407',
    projectId: 'flutter-project-6004e',
    storageBucket: 'flutter-project-6004e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNep-TmZUJYWX4uavaAosFPd0uff1PGho',
    appId: '1:609816954407:ios:026eed6d489998a3d63002',
    messagingSenderId: '609816954407',
    projectId: 'flutter-project-6004e',
    storageBucket: 'flutter-project-6004e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNep-TmZUJYWX4uavaAosFPd0uff1PGho',
    appId: '1:609816954407:ios:026eed6d489998a3d63002',
    messagingSenderId: '609816954407',
    projectId: 'flutter-project-6004e',
    storageBucket: 'flutter-project-6004e.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAacB0ISL3dOqTkyyetrI5jZ9Q53nEwdZk',
    appId: '1:609816954407:web:d1be54baf0ccf9ccd63002',
    messagingSenderId: '609816954407',
    projectId: 'flutter-project-6004e',
    authDomain: 'flutter-project-6004e.firebaseapp.com',
    storageBucket: 'flutter-project-6004e.firebasestorage.app',
    measurementId: 'G-WKKPL0LYHL',
  );
}
